spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/exedb
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 88
nginx:
  location: http://localhost/images/
image:
  baseDir: D:/nginx-1.16.2/html/images/

my:
  mail:
    host: smtp.gmail.com
    post: 587
    username: chunjyicj@gmail.com
    password: chungyi22
    properties:
      mail.smtp.starttls.enable: true